export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE = "GET_PROFILE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const GET_PROFILE_BY_HANDLE = "GET_PROFILE_BY_HANDLE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EDUCATION = "DELETE_EDUCATION";

export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
export const GET_PROFILE_API = "GET_PROFILE_API";
export const GET_PROFILE_ERRORS = "GET_PROFILE_ERRORS";
export const GET_PROFILES = "GET_PROFILES";
export const GET_PROFILES_API = "GET_PROFILES_API";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_POST = "GET_POST";
export const GET_POST_API = "GET_POST_API";
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_API = "GET_POSTS_API";
export const ADD_POST = "ADD_POST";
export const ADD_COMENT_API = "ADD_COMENT_API";
export const ADD_POST_API = "ADD_POST_API";
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_API = "DELETE_POST_API";
export const DELETE_COMMENT_API = "DELETE_COMMENT_API";
export const POST_LOADING = "POST_LOADING";
export const ADD_LIKE_POST_API = "ADD_LIKE_POST_API";
export const UN_LIKE_POST_API = "UN_LIKE_POST_API";
